### ISSUE TITLE
prescaler value rounds down so frequency rounds up, so frequency can be too high

### ISSUE THREAD

**Issue by ChrisIdema** [Reinbert/pca9685#2]
https://github.com/Reinbert/pca9685/blob/9f023c7220bbbb72e5ae54bd5e0152aa798585e8/src/pca9685.c#L104

I replaced it with 
`ceil((25E6/4096) /freq) -1`

This also removes one multiplication (although multiplying by 4096 is just shifting, but hey it is something).
This requires including math.h and linking against -lm.
An alternative would be:
```
#define CEILING(X) (X-(int)(X) > 0 ? (int)(X+1) : (int)(X))
CEILING((25E6/4096) /freq) -1
```

**Comment by Reinbert** [comment]
Hi @ChrisIdema!

I don't think you can substitute a multiplication with a division and expect a faster computation or compile time. 

Also, my code does not always round down.
The manual states the formula as `round(x) - 1`. You can also achieve a a round() function by adding 0.5 and then do an integer truncation, meaning `(int)(x + 0.5)`. Combining the -1 from the formula with the +0.5 from the truncation leaves us with 
`(int)(x - 0.5);`

As for your frequency problem: The module is not able to accurately reproduce all frequencies you tell it to. You can of course set the prescale to any value you seem fit, but with this library I will stick to the formula from the manual.

Cheers, Reinbert

**Comment by ChrisIdema** [comment]
> I don't think you can substitute a multiplication with a division and expect a faster computation or compile time.

That's not what I did at all! I replaced a division with a division. The numerator is still a compile time constant. And I removed the multiplication from the denominator.  You could easily rewrite it as `ceil( 25E6/ /(4096*freq) ) -1`. But I don't think that's faster.
Besides, this is pre-calculated during init, so not time critical anyway.

> Also, my code does not always round down.

Yes it does. It rounds to nearest which means it rounds down when the decimal part is less than 0.5. 

> The manual states the formula as round(x) - 1

The manual doesn't state the type of rounding (ceil, int or nearest). Your code rounds the prescaler down in some cases and therefore it rounds the frequency up.

Example:
```
  50Hz:    50.028 Hz (higher)
 100Hz:   100.057 Hz (higher)
 200Hz:   196.887 Hz (this one is ok)
 333Hz:   339.084 Hz (higher)
1000Hz:  1017.252 Hz (higher)
```

I needed 333 Hz in my application, but it was 6Hz above specifications. The higher the frequency the larger the error.

> As for your frequency problem: The module is not able to accurately reproduce all frequencies you tell it to.

Yes and that's why you need to compromise: either round it down or up. As an engineer I don't like to work out of spec and therefore I prefer to round down to a safe value. Some applications may need to round the frequency down and some may need to round it up. Personally I don't think the rounding will lead to many issues in practice, but I don't want to risk it.

> this library I will stick to the formula from the manual.

As long as this behavior is documented I can live with it.

**Comment by Reinbert** [comment]
> > Also, my code does not always round down.
> 
> Yes it does. It rounds to nearest which means it rounds down when the decimal part is less than 0.5.

And up if not. You have to round somewhere since the register only accepts integers. 


> > The manual states the formula as round(x) - 1
> 
> The manual doesn't state the type of rounding (ceil, int or nearest). Your code rounds the prescaler down in some cases and therefore it rounds the frequency up.

I would assume that the `round()` function from the manual is the same as the `round()` function in every programming language I know, since `floor()` and `ceil()` exist as well. 


> Example:
> 
> ```
>  333Hz:   339.084 Hz (higher)
> ```

What frequency does 332 give you?

**Comment by ChrisIdema** [comment]
> What frequency does 332 give you?

Your code gives 339.08Hz for the frequencies 330 to 348.  Mine gives 321 Hz if I put in 332. I compared it for a whole range of values and I didn't realize how big my rounding errors were.  For instance 339Hz is rounded to 321 Hz instead of 339.08.
I guess rounding to nearest is the safest for most applications after all. 
The only alternative solution I can come up with is to add a function to set the prescaler value directly to a custom value and a function to check the actual frequency and leave alternative roundings and  checks to the application.
